server {
    listen 8080;
    server_name 127.0.0.1;

    location /static/ {
        alias /var/www/static/;
    }

    location / {
        proxy_pass http://ctrl:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
