# Generated by Django 4.2.28 on 2026-02-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctrl', '0008_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='sequence_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='sequence_num',
            field=models.IntegerField(default=0),
        ),
    ]
