# Generated by Django 5.2.12 on 2026-03-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctrl', '0009_computer_location_sequencing'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='grid_col',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='grid_row',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='grid_cols',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
