# Generated by Django 5.2.12 on 2026-03-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctrl', '0010_grid_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('payload', models.TextField()),
            ],
        ),
    ]
